name: Update README with Unresolved Issues

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action every day at midnight.
  workflow_dispatch:  # Allows manual trigger of the workflow.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
   
    - name: Check Environment Variables
      run: |
        echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub

    - name: Run Python script
      run: python .github/scripts/update_readme.py
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git diff --staged | grep "README.md"; then
          git commit -m "Update README with Unresolved Issues"
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        else
          echo "No changes to README.md"
        fi
