name: Update README with Unresolved Issues

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action every day at midnight.
  workflow_dispatch:  # Allows manual trigger of the workflow.

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub

    - name: Run Python script
      run: python .github/scripts/update_readme_with_issues.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
